name: "daily-report"

on:
  schedule:
    - cron: '0 5 * * *' # Run at 5:00 AM UTC every day

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Generate report
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        shell: bash
        run: |
          # Define rpcs
          rpcs=(
            "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"          #     1 - Ethereum
            "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"          #    10 - Optimism
            "https://zksync-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"       #   324 - zkSync
            "https://polygonzkevm-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}" #  1101 - Polygon zkEVM
            "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"          # 42161 - Arbitrum One
            "https://arbnova-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"      # 42170 - Arbitrum Nova
          )
          # Generate report
          report="reports/report_$(date -u +"%Y-%m-%d").json"
          cargo run -- -r ${rpcs[@]} | jq > $report
          # Debugging
          echo "" && cat $report
          # Commit report to reports/ directory
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add reports/
          git commit -m "reports: Generated daily report"
          git push

