name: "daily-report"

on:
  schedule:
    - cron: '0 5 * * *' # Run at 5:00 AM UTC every day
  push: # Only for testing
    branches:
      - main

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Generate report
        env:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
        run: |
          # Define rpcs
          rpcs=(
            "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}" #  1 - Ethereum
            "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}" # 10 - Optimism
          )
          # Generate report
          cargo run -- -r $rpcs | jq > evm-blooms.json
          echo "" && cat evm-blooms.json                              # For better debugging
          # Commit report to
          git config --global user.name 'Github Actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          gid add evm-blooms.json
          git commit -m "reports: Daily report generation"
          git push

